import type { Metadata } from "next";
import Head from "next/head";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bebek Vagonu: İkinci El Bebek Ürünleri",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/favicon.ico",
      sizes: "16x16",
      type: "image/png",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Bebek Vagonu</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={inter.className} style={{ backgroundColor: 'white'}}>
        <div className='flex flex-col min-h-screen'>
          <Navbar/>
          <div className='h-1 ' style={{backgroundColor:'white'}}></div>
           <main className='flex-grow'>{children}</main>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
